### ISSUE TITLE
Controller Goal topic will change

### ISSUE THREAD

**Issue by mpomarlan** [SemRoCo/cl_giskard#1]
to include whether a new goal is sent for each body part or not. When that happens, update the wrapper (the goal mirrors can go away).

**Comment by airballking** [comment]
@mpomarlan I just finished implement this new feature. Please pull `giskard_msgs` and `giskard_examples` to try it out!

**Comment by mpomarlan** [comment]
Updated. The wrapper now uses the new giskard topics, but does not actually export the topic interface. Only the action interface is exposed. The topic interface is left in however to cover any future scenarios where we might need access to it from the user level.
