### ISSUE TITLE
Control stack exhausted (no more space for function call frames).

### ISSUE THREAD

**Issue by ghost** [SemRoCo/cl_giskard#6]
Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.
   [Condition of type SB-KERNEL::CONTROL-STACK-EXHAUSTED]

Restarts:
 0: [ABORT] Abort thread (#<THREAD "Subscriber thread for topic /controller_action_server/move/result" RUNNING {1005B360B3}>)

Backtrace:
  0: (SB-KERNEL::CONTROL-STACK-EXHAUSTED-ERROR)
      [No Locals]

i encountered this error after:
1.  `(swank:operate-on-system-for-emacs "cl-giskard" (quote load-op))`
2. `(roslisp-utilities:startup-ros)`
3. ```(cl-giskard:send-action-goal ... ...)

**Comment by mpomarlan** [comment]
Fixed by pull request #7
